"""schemas.ws_audio.rtvi_audio — RTVI 1.3.0 envelope for /ws/audio/{session_id}.

Implements the RTVI ``bot-tts-audio``, ``bot-tts-started``, and
``bot-tts-stopped`` message shapes as defined by the Pipecat RTVI 1.3.0 spec
(https://docs.pipecat.ai/server/rtvi/).

These models are sent as single JSON text frames over the audio WebSocket.
Unlike the legacy ``AudioHeaderFrame`` + binary-blob pair, each RTVI frame is
self-contained: PCM audio is base64-encoded inside the JSON payload.

Wire shape — ``bot-tts-audio``::

    {
      "label": "rtvi-ai",
      "type": "bot-tts-audio",
      "id": "550e8400-e29b-41d4-a716-446655440000",
      "data": {
        "audio": "<base64-encoded int16 PCM>",
        "sample_rate": 24000,
        "num_channels": 1
      }
    }

Wire shape — ``bot-tts-started``::

    {"label": "rtvi-ai", "type": "bot-tts-started", "id": "<uuid>", "data": {}}

Wire shape — ``bot-tts-stopped``::

    {"label": "rtvi-ai", "type": "bot-tts-stopped", "id": "<uuid>", "data": {}}

The ``id`` field is a fresh UUID per frame; clients may use it for
deduplication but are not required to.

Backward compatibility
----------------------
``AudioHeaderFrame`` (the legacy two-frame shape) is retained unchanged and
marked as deprecated in its docstring. Existing code that still emits that
shape will keep working. New code should use the RTVI envelope.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

# ---------------------------------------------------------------------------
# Shared envelope base
# ---------------------------------------------------------------------------

RTVI_LABEL: Literal["rtvi-ai"] = "rtvi-ai"


class _RtviBase(BaseModel):
    """Common fields shared by all RTVI server-to-client messages."""

    model_config = ConfigDict(populate_by_name=True, extra="allow")

    label: Literal["rtvi-ai"] = "rtvi-ai"
    id: str = Field(default="", description="Per-frame UUID; generated by the server.")


# ---------------------------------------------------------------------------
# bot-tts-audio
# ---------------------------------------------------------------------------


class BotTtsAudioData(BaseModel):
    """Payload carried inside a ``bot-tts-audio`` RTVI frame.

    ``audio`` is base64-encoded **int16 little-endian PCM** (not WAV — the
    44-byte RIFF header has been stripped).  ``sample_rate`` and
    ``num_channels`` describe the PCM stream so the client can construct an
    ``AudioBuffer`` without guessing.
    """

    model_config = ConfigDict(populate_by_name=True)

    audio: str = Field(description="base64-encoded int16 PCM samples (no RIFF header)")
    sample_rate: int = Field(default=24000, gt=0)
    num_channels: int = Field(default=1, ge=1)


class RtviBotTtsAudio(_RtviBase):
    """RTVI ``bot-tts-audio`` server frame.

    One frame per audio chunk emitted by the TTS engine.  The client
    decodes ``data.audio`` from base64 to raw int16 PCM and feeds it to
    the audio pipeline (e.g. ``AudioPlayback.enqueue()``).

    Wire shape::

        {
          "label": "rtvi-ai",
          "type": "bot-tts-audio",
          "id": "...",
          "data": {
            "audio": "<base64>",
            "sample_rate": 24000,
            "num_channels": 1
          }
        }
    """

    type: Literal["bot-tts-audio"] = "bot-tts-audio"
    data: BotTtsAudioData


# ---------------------------------------------------------------------------
# bot-tts-started
# ---------------------------------------------------------------------------


class RtviBotTtsStarted(_RtviBase):
    """RTVI ``bot-tts-started`` marker frame.

    Emitted before the first ``bot-tts-audio`` chunk in an utterance.
    Clients should use this to clear any existing playback queue and
    prepare for incoming audio.

    Wire shape::

        {"label": "rtvi-ai", "type": "bot-tts-started", "id": "...", "data": {}}
    """

    type: Literal["bot-tts-started"] = "bot-tts-started"
    data: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# bot-tts-stopped
# ---------------------------------------------------------------------------


class RtviBotTtsStopped(_RtviBase):
    """RTVI ``bot-tts-stopped`` marker frame.

    Emitted after the last ``bot-tts-audio`` chunk in an utterance.
    Clients can use this to mark the end of the audio stream and update
    playback state accordingly.

    Wire shape::

        {"label": "rtvi-ai", "type": "bot-tts-stopped", "id": "...", "data": {}}
    """

    type: Literal["bot-tts-stopped"] = "bot-tts-stopped"
    data: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Union type for incoming consumers
# ---------------------------------------------------------------------------

RtviAudioFrame = RtviBotTtsAudio | RtviBotTtsStarted | RtviBotTtsStopped

__all__ = [
    "BotTtsAudioData",
    "RTVI_LABEL",
    "RtviAudioFrame",
    "RtviBotTtsAudio",
    "RtviBotTtsStarted",
    "RtviBotTtsStopped",
]
